version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crud
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crud-django
    # command: sh -c "python wait-for-it.py && python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:3001"
    command: sh -c "python wait-for-it.py && python manage.py makemigrations app && python manage.py migrate && gunicorn project.wsgi:application --bind 0.0.0.0:3001"
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - mynetwork

  frontend:
    image: karthikeya2100/crud-react:latest
    container_name: crud-react
    environment:
      # - API_URL=http://localhost:3001
      - API_URL=https://crud-app.run.place/django
      - BACKEND_FRAMEWORK=Django and MySQL
      - TITLE=CRUD-Django
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app/dist  

networks:
  mynetwork:
